var Constants = {
  ADD_POSTENTRY: "ADD_POSTENTRY",
  REMOVE_POSTENTRY: "REMOVE_POSTENTRY",
  RELOAD_POSTLIST:'RELOAD_POSTLIST',
  STORE_UPDATED:"STORE_UPDATED",
  PULL_POSTLIST:'PULL_POSTLIST'
};

module.exports = Constants;
