var Constants = {
  ADD_IDEA           : 'ADD_IDEA',
  ADD_COMMENT        : 'ADD_COMMENT',
  REMOVE_IDEA        : 'REMOVE_IDEA',
  REMOVE_COMMENT     : 'REMOVE_COMMENT',
  RELOAD_IDEALIST    : 'RELOAD_IDEALIST',
  RELOAD_COMMENTLIST : 'RELOAD_COMMENTLIST',
  FETCH_IDEALIST     : 'FETCH_IDEALIST',
  FETCH_COMMENTLIST  : 'FETCH_COMMENTLIST',
  STORE_UPDATED      : 'STORE_UPDATED',
  RELOAD_USER        : 'RELOAD_USER'
};

module.exports = Constants;

